cacheFolder: ./.yarn/cache

httpTimeout: 60000

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-licenses.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-licenses/v0.7.2/bundles/@yarnpkg/plugin-licenses.js"

yarnPath: .yarn/releases/yarn-berry.cjs
